# Generated by Django 4.1.1 on 2022-12-05 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'developers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'genre',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'publishers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('activated', models.BooleanField()),
                ('activationCode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('releasedate', models.DateField(blank=True, db_column='releaseDate', null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('developer', models.ManyToManyField(to='lab3_app.developers')),
                ('genre', models.ManyToManyField(to='lab3_app.genre')),
                ('publisher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lab3_app.publishers')),
            ],
            options={
                'db_table': 'game',
                'managed': True,
            },
        ),
    ]
