# Generated by Django 4.1.1 on 2022-12-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_app', '0004_alter_users_managers_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
