# Generated by Django 4.1.1 on 2022-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_app', '0008_users_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='managed_by',
            field=models.BigIntegerField(default=6),
        ),
    ]
