# Generated by Django 4.1.1 on 2022-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_app', '0011_remove_game_developer_alter_game_publisher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
