# Generated by Django 4.1.1 on 2023-01-11 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3_app', '0014_alter_library_activation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
